name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install wasm-pack
        run: |
          npm install -g wasm-pack

      - name: Build wasm module
        run: |
          cd ./chroma-wasm
          wasm-pack build --target web

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Link project to Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
        run: |
          echo "y" | npx vercel link --token $VERCEL_TOKEN --project $VERCEL_PROJECT_ID --confirm

      - name: Deploy to Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: |
          npx vercel --prod --token $VERCEL_TOKEN
